apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orbitops
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: orbitops-copilot
resources:
  - namespace.yaml
  - scenario-configmap.yaml
  - emulator-deployment.yaml
  - emulator-service.yaml
  - copilot-deployment.yaml
  - copilot-service.yaml
  - ui-deployment.yaml
