kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: orbitops
nodes:
  - role: control-plane
    extraPortMappings:
      # emulator → host
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # copilot-api → host
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
      # ui → host
      - containerPort: 30073
        hostPort: 30073
        protocol: TCP
