// Mirror of services/copilot-api response schema (v2 / ADR-007).
// Generated by hand to avoid runtime json-schema-to-typescript dep on Sprint 1.

export type CopilotStatus = "ok" | "INSUFFICIENT_EVIDENCE" | "REFUSED" | "ERROR";

export interface MetricCitation {
  name: string;
  labels: Record<string, string>;
  value: number;
  timestamp: string;
}

export interface LogCitation {
  source: string;
  line: string;
  timestamp: string;
}

export interface Evidence {
  metrics_used: MetricCitation[];
  logs_used: LogCitation[];
  scenario_id: string | null;
  time_window_seconds: number | null;
  timestamp: string;
}

export interface RecommendedAction {
  step: number;
  title: string;
  body: string;
}

export interface CopilotResponse {
  summary: string | null;
  likely_cause: string | null;
  evidence: Evidence;
  recommended_actions: RecommendedAction[];
  risk_if_ignored: string | null;
  confidence: number;
  unknowns: string[];
  status: CopilotStatus;
  refusal_reason: string | null;
  error: string | null;
}

// Local UI domain types (not from copilot-api).
export type BeamHealth = "ok" | "warn" | "crit";

export interface BeamView {
  beam_id: string;
  snr_db: number;
  sinr_db: number;
  latency_ms: number;
  packet_loss_ratio: number;
  doppler_residual_hz: number;
  handover_state: 0 | 1 | 2;
  // Per-beam elevation in degrees (0..90); sourced from orbitops_beam_elevation_deg.
  // Sin-shaped over scenario.duration_seconds with peak from
  // scenario.satellite.pass_peak_elevation_deg (default 55°). Producer clamps
  // to [0, 90] regardless of input. Added in PR #34 (G7) — UI surface
  // landed in PR-Phase-H.1.1.
  elevation_deg: number;
  health: BeamHealth;
}

export interface GatewayView {
  gateway_id: string;
  available: boolean; // backed by orbitops_gateway_available
  load: number | null; // 0..1; null when not exported
}

export interface MetricsSnapshot {
  scenario_id: string;
  t_seconds: number;
  beams: BeamView[];
  gateways: GatewayView[];
  active_anomaly: string | null; // e.g. "snr_drop", or null
  active_anomalies: string[]; // multi-anomaly listing (Sprint 2 forward-compat)
  scraped_at: string; // ISO timestamp
}

// Parsed Prometheus metric line (one per gauge sample).
export interface PromSample {
  name: string;
  labels: Record<string, string>;
  value: number;
}

// Producer event types per scenario.schema.json events.type enum.
// Mirrors the 5 valid `type` values accepted by POST /anomaly/inject.
export type AnomalyType =
  | "snr_drop"
  | "handover_failure"
  | "doppler_spike"
  | "gateway_outage"
  | "packet_loss_spike";

// Request body for POST /anomaly/inject.
export interface InjectAnomalyInput {
  type: AnomalyType;
  target?: string;
  duration_seconds?: number;
  magnitude_db?: number;
  magnitude_hz?: number;
}

// Response body — mirrors the emulator's /anomaly/inject response.
export interface InjectAnomalyResult {
  type: string;
  target: string;
  t_start: number;
  t_end: number;
  duration_seconds: number;
  currently_active: string[];
}

// ── VS-21 closed-loop dry-run (Sprint-5) ──────────────────────────────────
// Mirrors copilot-api GET /action/catalog + POST /action/dry-run.
export interface ActionParamSpec {
  name: string;
  kind: "int" | "enum";
  min?: number;
  max?: number;
  options?: string[];
  default?: number | string;
}

export interface ActionCatalogItem {
  action_id: string;
  description: string;
  target_resource: string;
  inverse_action_id: string | null;
  params_spec: ActionParamSpec[];
}

export interface ActionDryRun {
  action_id: string;
  params: Record<string, unknown>;
  target_resource: string;
  patch: Record<string, unknown>;
  diff: string;
  inverse_action_id: string | null;
  dry_run: boolean;
  note: string;
}
