// Mirror of services/copilot-api response schema (v2 / ADR-007).
// Generated by hand to avoid runtime json-schema-to-typescript dep on Sprint 1.

export type CopilotStatus = "ok" | "INSUFFICIENT_EVIDENCE" | "REFUSED" | "ERROR";

export interface MetricCitation {
  name: string;
  labels: Record<string, string>;
  value: number;
  timestamp: string;
}

export interface LogCitation {
  source: string;
  line: string;
  timestamp: string;
}

export interface Evidence {
  metrics_used: MetricCitation[];
  logs_used: LogCitation[];
  scenario_id: string | null;
  time_window_seconds: number | null;
  timestamp: string;
}

export interface RecommendedAction {
  step: number;
  title: string;
  body: string;
}

export interface CopilotResponse {
  summary: string | null;
  likely_cause: string | null;
  evidence: Evidence;
  recommended_actions: RecommendedAction[];
  risk_if_ignored: string | null;
  confidence: number;
  unknowns: string[];
  status: CopilotStatus;
  refusal_reason: string | null;
  error: string | null;
}

// Local UI domain types (not from copilot-api).
export type BeamHealth = "ok" | "warn" | "crit";

export interface BeamView {
  beam_id: string;
  snr_db: number;
  sinr_db: number;
  latency_ms: number;
  packet_loss_ratio: number;
  doppler_residual_hz: number;
  handover_state: 0 | 1 | 2;
  health: BeamHealth;
}

export interface MetricsSnapshot {
  scenario_id: string;
  t_seconds: number;
  beams: BeamView[];
  active_anomaly: string | null; // e.g. "snr_drop", or null
}
