apiVersion: v1
kind: Service
metadata:
  name: copilot-api
  labels:
    app.kubernetes.io/name: copilot-api
spec:
  selector:
    app.kubernetes.io/name: copilot-api
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
